name: clean_architecture_kit
description: >-
  A custom linter to enforce Clean Architecture principles in Dart and Flutter projects, with code 
  actions to streamline development.
version: 1.0.1

repository: https://github.com/puntbyte/clean_architecture_kit
homepage: https://github.com/puntbyte/clean_architecture_kit

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ">=8.0.0 <9.0.0"
  code_builder: ^4.10.0
  custom_lint_builder: ">=0.7.0 <1.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

  # This package is used by the MissingUseCase lint
  # ignore: implementation_imports
  analyzer_plugin: ">=0.12.0 <1.0.0"

dev_dependencies:
  lints: ^6.0.0
