name: clean_architecture_kit
description: >-
  A custom linter to enforce Clean Architecture principles in Dart and Flutter projects, with code 
  actions to streamline development.
version: 1.0.0

repository: https://github.com/puntbyte/clean_architecture_kit

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.0.0
  code_builder: ^4.11.0
  custom_lint_builder: ^0.8.0
  dart_style: ^3.1.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

  # This package is used by the MissingUseCase lint
  # ignore: implementation_imports
  analyzer_plugin: ^0.13.5

dev_dependencies:
  lints: ^6.0.0
